name: glacier-fronts
channels:
  - conda-forge
  - pytorch
  - fastai
  - nodefaults
dependencies:
  - conda-forge::ipykernel=5.2.0
  - conda-forge::ipywidgets=7.5.1
  - pytorch::torchvision=0.5.0
  - fastai::fastai=1.0.60